### ISSUE TITLE
我们学校貌似升级过没有免验证码接口！

### ISSUE THREAD

**Issue by 178620086** [liaol/weixin-zhengfang#1]
jw.svtcc.edu.cn

能帮我看看其他的办法么？？？

**Comment by liaol** [comment]
那就识别验证码喽

**Comment by 178620086** [comment]
你这个是参加中国软件杯的项目么？

**Comment by liaol** [comment]
不是 
兴趣而已

可用于iOS的myMail发送


2015年10月29日 星期四 +0800 18:47 发件人 Tmo  <notifications@github.com>:
